// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtu8oEp4h5Nd-ls_GpZ3nCbIpG1hrcs9c',
    appId: '1:935760698718:web:70399cf6e47f74358bc3cf',
    messagingSenderId: '935760698718',
    projectId: 'whatsapp-637be',
    authDomain: 'whatsapp-637be.firebaseapp.com',
    storageBucket: 'whatsapp-637be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoqWo-9CJd-nT9DdPys0BLWkJdZbTlqsQ',
    appId: '1:935760698718:android:e236e91f2a7e42a78bc3cf',
    messagingSenderId: '935760698718',
    projectId: 'whatsapp-637be',
    storageBucket: 'whatsapp-637be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCINsgm1uUVS_v3oX3-xnnOcPoTplAElo0',
    appId: '1:935760698718:ios:34af53ae44eec7a68bc3cf',
    messagingSenderId: '935760698718',
    projectId: 'whatsapp-637be',
    storageBucket: 'whatsapp-637be.appspot.com',
    iosClientId: '935760698718-fpb5od1iejj0afi2vr1c6m5c5rkaarh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCINsgm1uUVS_v3oX3-xnnOcPoTplAElo0',
    appId: '1:935760698718:ios:34af53ae44eec7a68bc3cf',
    messagingSenderId: '935760698718',
    projectId: 'whatsapp-637be',
    storageBucket: 'whatsapp-637be.appspot.com',
    iosClientId: '935760698718-fpb5od1iejj0afi2vr1c6m5c5rkaarh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappMessenger',
  );
}
